# Generated by Django 5.0.6 on 2024-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subtitle',
            field=models.TextField(max_length=200, verbose_name='Subtitulo'),
        ),
    ]
